USE [AlbertaProductionDB]
GO

/****** Object:  Table [dbo].[Source_Well_Infrastructure]    Script Date: 2026-09-28 10:22:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Source_Well_Infrastructure](
	[Well_ID] [nvarchar](20) NOT NULL,
	[Well_Province_State] [nchar](2) NOT NULL,
	[Well_Type] [nchar](2) NOT NULL,
	[Well_Identifier] [nvarchar](16) NOT NULL,
	[Well_Location_Exception] [nchar](2) NOT NULL,
	[Well_Legal_Subdivision] [tinyint] NULL,
	[Well_Section] [tinyint] NOT NULL,
	[Well_Township] [tinyint] NOT NULL,
	[Well_Range] [tinyint] NOT NULL,
	[Well_Meridian] [tinyint] NOT NULL,
	[Well_Event_Sequence] [tinyint] NOT NULL,
	[Well_Name] [nvarchar](36) NULL,
	[Confidential_Type] [nvarchar](18) NOT NULL,
	[Experimental_Confidential_Indicator] [nchar](1) NOT NULL,
	[Experimental_Confidential_Effective_Date] [date] NULL,
	[Experimental_Confidential_Termination_Date] [date] NULL,
	[Licence_Type] [nvarchar](4) NOT NULL,
	[Licence_Number] [nvarchar](9) NOT NULL,
	[Linked_Facility_ID] [nvarchar](11) NULL,
	[Linked_Facility_Province_State] [nchar](2) NULL,
	[Linked_Facility_Type] [nchar](2) NULL,
	[Linked_Facility_Identifier] [nvarchar](7) NULL,
	[Linked_Facility_Name] [nvarchar](36) NULL,
	[Linked_Facility_Sub_Type] [nvarchar](3) NULL,
	[Linked_Facility_Sub_Type_Desc] [nvarchar](58) NULL,
	[Linked_Start_Date] [date] NULL,
	[Linked_Facility_Operator_BAID] [nvarchar](4) NULL,
	[Linked_Facility_Operator_Legal_Name] [nvarchar](97) NULL,
	[Field_Code] [nchar](4) NOT NULL,
	[Field_Name] [nvarchar](20) NOT NULL,
	[Area_Code] [nchar](4) NULL,
	[Area_Name] [nvarchar](18) NULL,
	[Pool_Deposit_Code] [nvarchar](7) NULL,
	[Pool_Deposit_Name] [nvarchar](21) NULL,
	[Pool_Deposit_Density] [nvarchar](5) NULL,
	[Well_Status_Fluid] [nvarchar](7) NOT NULL,
	[Well_Status_Mode] [nvarchar](8) NOT NULL,
	[Well_Status_Type] [nvarchar](6) NOT NULL,
	[Well_Status_Structure] [nvarchar](11) NOT NULL,
	[Well_Status_Fluid_Code] [nchar](2) NOT NULL,
	[Well_Status_Mode_Code] [nchar](2) NOT NULL,
	[Well_Status_Type_Code] [nchar](2) NOT NULL,
	[Well_Status_Structure_Code] [nchar](2) NOT NULL,
	[Well_Status_Date] [date] NOT NULL,
	[Spud_Date] [date] NULL,
	[Horizontal_Drill] [nvarchar](13) NULL,
	[Finished_Drill_Date] [date] NULL,
	[Final_Total_Depth] [decimal](13, 9) NULL,
	[Max_True_Vertical_Depth] [decimal](13, 9) NULL,
	[Volumetric_Gas_Well_Liquid_Type] [nvarchar](10) NULL,
	[Volumetric_Gas_Well_Liquid_Effective_Date] [date] NULL,
	[Licensee_ID] [nvarchar](4) NOT NULL,
	[Licensee_Name] [nvarchar](97) NOT NULL,
	[Commingling_Process_Approval_Number] [nvarchar](10) NULL,
	[Commingling_Process] [nvarchar](4) NULL,
	[Commingling_Effective_Date] [date] NULL,
	[Commingled_Reporting_Well_ID] [nvarchar](20) NULL,
	[Commingled_Reporting_Well_Province_State] [nchar](2) NULL,
	[Commingled_Reporting_Well_Type] [nchar](2) NULL,
	[Commingled_Reporting_Well_Identifier] [nvarchar](16) NULL,
	[Commingled_Linked_Facility_ID] [nvarchar](11) NULL,
	[Commingled_Linked_Facility_Province_State] [nchar](2) NULL,
	[Commingled_Linked_Facility_Type] [nchar](2) NULL,
	[Commingled_Linked_Facility_Identifier] [nvarchar](7) NULL,
	[Allowable_Type] [nvarchar](24) NOT NULL,
	[Block_Number] [tinyint] NULL,
	[Recovery_Mechanism_Type] [nvarchar](20) NULL,
	[Licence_Issue_Date] [date] NOT NULL,
	[Licence_Status_Date] [date] NULL,
	[Licence_Status] [nvarchar](12) NOT NULL,
	[Previous_Well_ID] [nvarchar](16) NULL,
	[Orphan_Well_Flag] [nchar](1) NOT NULL
) ON [PRIMARY]
GO
