USE [AlbertaProductionDB]
GO

/****** Object:  Table [dbo].[Staging_Well_Infrastructure]    Script Date: 2026-09-28 10:37:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Staging_Well_Infrastructure](
	[WellID] [nvarchar](150) NULL,
	[WellProvinceState] [nvarchar](150) NULL,
	[WellType] [nvarchar](150) NULL,
	[WellIdentifier] [nvarchar](150) NULL,
	[WellLocationException] [nvarchar](150) NULL,
	[WellLegalSubdivision] [nvarchar](150) NULL,
	[WellSection] [nvarchar](150) NULL,
	[WellTownship] [nvarchar](150) NULL,
	[WellRange] [nvarchar](150) NULL,
	[WellMeridian] [nvarchar](150) NULL,
	[WellEventSequence] [nvarchar](150) NULL,
	[WellName] [nvarchar](150) NULL,
	[ConfidentialType] [nvarchar](150) NULL,
	[ExperimentalConfidentialIndicator] [nvarchar](150) NULL,
	[ExperimentalConfidentialEffectiveDate] [nvarchar](150) NULL,
	[ExperimentalConfidentialTerminationDate] [nvarchar](150) NULL,
	[LicenceType] [nvarchar](150) NULL,
	[LicenceNumber] [nvarchar](150) NULL,
	[LinkedFacilityID] [nvarchar](150) NULL,
	[LinkedFacilityProvinceState] [nvarchar](150) NULL,
	[LinkedFacilityType] [nvarchar](150) NULL,
	[LinkedFacilityIdentifier] [nvarchar](150) NULL,
	[LinkedFacilityName] [nvarchar](150) NULL,
	[LinkedFacilitySubType] [nvarchar](150) NULL,
	[LinkedFacilitySubTypeDesc] [nvarchar](150) NULL,
	[LinkedStartDate] [nvarchar](150) NULL,
	[LinkedFacilityOperatorBAID] [nvarchar](150) NULL,
	[LinkedFacilityOperatorLegalName] [nvarchar](150) NULL,
	[Field] [nvarchar](150) NULL,
	[FieldName] [nvarchar](150) NULL,
	[Area] [nvarchar](150) NULL,
	[AreaName] [nvarchar](150) NULL,
	[PoolDeposit] [nvarchar](150) NULL,
	[PoolDepositName] [nvarchar](150) NULL,
	[PoolDepositDensity] [nvarchar](150) NULL,
	[WellStatusFluid] [nvarchar](150) NULL,
	[WellStatusMode] [nvarchar](150) NULL,
	[WellStatusType] [nvarchar](150) NULL,
	[WellStatusStructure] [nvarchar](150) NULL,
	[WellStatusFluidCode] [nvarchar](150) NULL,
	[WellStatusModeCode] [nvarchar](150) NULL,
	[WellStatusTypeCode] [nvarchar](150) NULL,
	[WellStatusStructureCode] [nvarchar](150) NULL,
	[WellStatusDate] [nvarchar](150) NULL,
	[SpudDate] [nvarchar](150) NULL,
	[HorizontalDrill] [nvarchar](150) NULL,
	[FinishedDrillDate] [nvarchar](150) NULL,
	[FinalTotalDepth] [nvarchar](150) NULL,
	[MaxTrueVerticalDepth] [nvarchar](150) NULL,
	[VolumetricGasWellLiquidType] [nvarchar](150) NULL,
	[VolumetricGasWellLiquidEffectiveDate] [nvarchar](150) NULL,
	[LicenseeID] [nvarchar](150) NULL,
	[LicenseeName] [nvarchar](150) NULL,
	[ComminglingProcessApprovalNumber] [nvarchar](150) NULL,
	[ComminglingProcess] [nvarchar](150) NULL,
	[ComminglingEffDate] [nvarchar](150) NULL,
	[CommingledReportingWellID] [nvarchar](150) NULL,
	[CommingledReportingWellProvinceState] [nvarchar](150) NULL,
	[CommingledReportingWellType] [nvarchar](150) NULL,
	[CommingledReportingWellIdentifier] [nvarchar](150) NULL,
	[CommingledLinkedFacilityID] [nvarchar](150) NULL,
	[CommingledLinkedFacilityProvinceState] [nvarchar](150) NULL,
	[CommingledLinkedFacilityType] [nvarchar](150) NULL,
	[CommingledLinkedFacilityIdentifier] [nvarchar](150) NULL,
	[AllowableType] [nvarchar](150) NULL,
	[BlockNumber] [nvarchar](150) NULL,
	[RecoveryMechanismType] [nvarchar](150) NULL,
	[LicenceIssueDate] [nvarchar](150) NULL,
	[LicenceStatusDate] [nvarchar](150) NULL,
	[LicenceStatus] [nvarchar](150) NULL,
	[PreviousWellID] [nvarchar](150) NULL,
	[OrphanWellFlg] [nvarchar](150) NULL
) ON [PRIMARY]
GO
